/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendaangelitodesktop;

import dao.Categoria;
import dao.Producto;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arnold
 */
public class FrmAdministrarProducto extends javax.swing.JDialog {
    Producto prod =new Producto();
    Categoria cat = new Categoria();
    DefaultTableModel model; 

    
    /**
     * Creates new form FrmAdministrarProducto
     * @param parent
     * @param modal
     */
    public FrmAdministrarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenarTabla();
        llenarCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCategorias = new javax.swing.JPanel();
        lblCategoria = new javax.swing.JLabel();
        txfCodProducto = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        lblBuscar = new javax.swing.JLabel();
        txfBuscar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        tblProductos = new javax.swing.JScrollPane();
        jtblProductos = new javax.swing.JTable();
        txfNomProducto = new javax.swing.JTextField();
        lblCategoria1 = new javax.swing.JLabel();
        lblCategoria2 = new javax.swing.JLabel();
        txfPrecDetalle = new javax.swing.JTextField();
        lblCategoria3 = new javax.swing.JLabel();
        txfPrecMayoreo = new javax.swing.JTextField();
        lblCategoria4 = new javax.swing.JLabel();
        txfIva = new javax.swing.JTextField();
        lblCategoria5 = new javax.swing.JLabel();
        txfMinMayoreo = new javax.swing.JTextField();
        lblCategoria6 = new javax.swing.JLabel();
        txfExistencia = new javax.swing.JTextField();
        lblCategoria7 = new javax.swing.JLabel();
        txfAlerta = new javax.swing.JTextField();
        lblCategoria8 = new javax.swing.JLabel();
        lblCategoria9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txfDescProducto = new javax.swing.JTextArea();
        lblCategoria10 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        lblCategoria11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlCategorias.setBorder(javax.swing.BorderFactory.createTitledBorder("Adiministración de Productos"));

        lblCategoria.setText("Código de Producto:");

        txfCodProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnAgregar.setText("Agregar Nuevo Producto");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        lblBuscar.setText("Buscar:");

        txfBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfBuscarKeyReleased(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jtblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProductos.setViewportView(jtblProductos);

        lblCategoria1.setText("Nombre del Producto:");

        lblCategoria2.setText("Descripción");

        lblCategoria3.setText("Precio Detalle:");

        lblCategoria4.setText("Precio Mayoreo:");

        lblCategoria5.setText("IVA Aplicable:");

        lblCategoria6.setText("Cantidad Mínima de Mayoreo:");

        txfExistencia.setEnabled(false);

        lblCategoria7.setText("Existencia:");

        lblCategoria8.setText("Avisar cuando queden");

        lblCategoria9.setText("Categoría:");

        txfDescProducto.setColumns(20);
        txfDescProducto.setRows(5);
        jScrollPane1.setViewportView(txfDescProducto);

        lblCategoria10.setText("%");

        lblCategoria11.setText("en existencia");

        javax.swing.GroupLayout pnlCategoriasLayout = new javax.swing.GroupLayout(pnlCategorias);
        pnlCategorias.setLayout(pnlCategoriasLayout);
        pnlCategoriasLayout.setHorizontalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblProductos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCategoriasLayout.createSequentialGroup()
                        .addComponent(lblBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txfBuscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCategoriasLayout.createSequentialGroup()
                        .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                                .addComponent(lblCategoria)
                                .addGap(18, 18, 18)
                                .addComponent(txfCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCategoria1)
                                    .addComponent(lblCategoria2))
                                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlCategoriasLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txfNomProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCategoriasLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(34, 34, 34)
                        .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCategoriasLayout.createSequentialGroup()
                                .addComponent(lblCategoria6)
                                .addGap(18, 18, 18)
                                .addComponent(txfMinMayoreo)
                                .addGap(26, 26, 26))
                            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                                .addComponent(lblCategoria3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txfPrecDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCategoriasLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfExistencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCategoriasLayout.createSequentialGroup()
                                        .addComponent(lblCategoria9)
                                        .addGap(37, 37, 37)
                                        .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCategoria5)
                                    .addComponent(lblCategoria4))
                                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlCategoriasLayout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addComponent(txfIva)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCategoria10)
                                        .addGap(30, 30, 30))
                                    .addGroup(pnlCategoriasLayout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(txfPrecMayoreo))))
                            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCategoria7)
                                    .addGroup(pnlCategoriasLayout.createSequentialGroup()
                                        .addComponent(lblCategoria8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txfAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCategoria11)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCategoriasLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCategoriasLayout.createSequentialGroup()
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCategoriasLayout.createSequentialGroup()
                                .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                .addGap(237, 237, 237)))))
                .addGap(0, 0, 0))
        );
        pnlCategoriasLayout.setVerticalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCategoriasLayout.createSequentialGroup()
                        .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategoria)
                            .addComponent(txfCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria3)
                            .addComponent(txfPrecDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategoria1)
                            .addComponent(txfNomProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCategoria4)
                        .addComponent(txfPrecMayoreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCategoria2)
                    .addGroup(pnlCategoriasLayout.createSequentialGroup()
                        .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategoria5)
                            .addComponent(txfIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfMinMayoreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCategoria6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategoria7)
                            .addComponent(txfExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategoria8)
                            .addComponent(txfAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategoria9)
                            .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(tblProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCategorias.getAccessibleContext().setAccessibleName("Administración de Productos");
        pnlCategorias.getAccessibleContext().setAccessibleDescription("");

        getAccessibleContext().setAccessibleName("Administración de Productos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        
        String codigo;
        String nombre;
        String descripcion;
        double precioDetalle;
        double precioMayoreo;
        double iva;
        int cantidadMinima;
        int alerta;
        
        int codigoExistente=0;
        int categoriaInt=1;
        String categoriaS;
        ResultSet rst = null;
        ResultSet codigoReg=null;
        //
        
        
        if (txfCodProducto.getText()==""||txfNomProducto.getText()==""
                ||txfPrecDetalle.getText()==""
                ||txfPrecMayoreo.getText()==""||txfIva.getText()==""
                ||txfMinMayoreo.getText()==""||txfAlerta.getText()=="") {
            JOptionPane.showMessageDialog(null, "Por favor, introduzca todos los datos obligatorios", 
                    null, JOptionPane.ERROR_MESSAGE);
            
            
        } else {
            codigo= txfCodProducto.getText();
            
            categoriaS = cmbCategoria.getSelectedItem().toString();
            rst = prod.obtenerIdCategoria(categoriaS);
            codigoReg=prod.obtenerCodigos(codigo);
            try {
                while (rst.next()){
                    categoriaInt =rst.getInt(1);
                }
                while (codigoReg.next()){
                    codigoExistente=codigoReg.getInt(1);
                }
            
                if (codigoExistente == 0){
                    nombre= txfNomProducto.getText();
                    descripcion=txfDescProducto.getText();
                    precioDetalle=Double.parseDouble(txfPrecDetalle.getText());
                    precioMayoreo=Double.parseDouble(txfPrecMayoreo.getText());
                    iva=Double.parseDouble(txfIva.getText());
                    cantidadMinima=Integer.parseInt(txfMinMayoreo.getText());
                    alerta=Integer.parseInt(txfAlerta.getText());
                    
                    prod.agregarProducto(codigo, nombre, descripcion, precioDetalle, precioMayoreo, iva, cantidadMinima, alerta, categoriaInt);
                    
                    llenarTabla();
                    JOptionPane.showMessageDialog(null, "Producto ingresado de forma exitosa");
                    
                    txfCodProducto.setText("");
                    txfNomProducto.setText("");
                    txfDescProducto.setText("");
                    txfPrecDetalle.setText("");
                    txfPrecMayoreo.setText("");
                    txfIva.setText("");
                    txfMinMayoreo.setText("");
                    txfExistencia.setText("");
                    txfAlerta.setText("");
                    cmbCategoria.setSelectedIndex(0);
                    txfCodProducto.requestFocus();
                }else{
                    JOptionPane.showMessageDialog(null, "Código de Producto Existente.", null, JOptionPane.ERROR_MESSAGE);
                    
                }
            
            
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
            }
         
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        JOptionPane.showMessageDialog(this, "Opción en Desarrollo");
//        int idProducto;
//        String categoria;
//
//        if(tblCategoria.getSelectedRow()!=-1){
//            idCategoria = Integer.parseInt(tblCategoria.getValueAt(tblCategoria.getSelectedRow(), 0).toString());
//            categoria = (String) tblCategoria.getValueAt(tblCategoria.getSelectedRow(), 1);
//
//            FrmEditarCategoria ed = new FrmEditarCategoria(new java.awt.Frame(), true, cat, idCategoria, categoria);
//            ed.setVisible(true);
//
//        } else {
//            JOptionPane.showMessageDialog(this, "Seleccione el registro que desea editar");
//        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txfBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfBuscarKeyReleased

        JOptionPane.showMessageDialog(this, "Opción en Desarrollo");
//        String filtro = txfBuscar.getText();
//        filtrarTabla(filtro);
    }//GEN-LAST:event_txfBuscarKeyReleased

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        JOptionPane.showMessageDialog(this, "Opción en Desarrollo");
//        String idProducto;
//
//        if(jtblProductos.getSelectedRow()!=-1){
//            idProducto = String.valueOf(model.getValueAt(jtblProductos.getSelectedRow()),0);
//            String dato=String.valueOf(tm.getValueAt(tabla1.getSelectedRow(),0));
//            
//            cat.eliminarCategoria(idCategoria);
//        } else {
//            JOptionPane.showMessageDialog(this, "Seleccione el registro que desea eliminar");
//        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmAdministrarProducto dialog = new FrmAdministrarProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblProductos;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCategoria1;
    private javax.swing.JLabel lblCategoria10;
    private javax.swing.JLabel lblCategoria11;
    private javax.swing.JLabel lblCategoria2;
    private javax.swing.JLabel lblCategoria3;
    private javax.swing.JLabel lblCategoria4;
    private javax.swing.JLabel lblCategoria5;
    private javax.swing.JLabel lblCategoria6;
    private javax.swing.JLabel lblCategoria7;
    private javax.swing.JLabel lblCategoria8;
    private javax.swing.JLabel lblCategoria9;
    private javax.swing.JPanel pnlCategorias;
    private javax.swing.JScrollPane tblProductos;
    private javax.swing.JTextField txfAlerta;
    private javax.swing.JTextField txfBuscar;
    private javax.swing.JTextField txfCodProducto;
    private javax.swing.JTextArea txfDescProducto;
    private javax.swing.JTextField txfExistencia;
    private javax.swing.JTextField txfIva;
    private javax.swing.JTextField txfMinMayoreo;
    private javax.swing.JTextField txfNomProducto;
    private javax.swing.JTextField txfPrecDetalle;
    private javax.swing.JTextField txfPrecMayoreo;
    // End of variables declaration//GEN-END:variables

    private void llenarTabla() {
        Object datos[] = new Object[9];
        ResultSet rst = null;
        rst = prod.mostrarProductos();
        model = new DefaultTableModel();
        model.addColumn("Producto");
        model.addColumn("Precio Detalle");
        model.addColumn("Precio Mayoreo");
        model.addColumn("IVA");
        model.addColumn("Cantidad de Mayoreo");
        model.addColumn("Existencia");
        model.addColumn("Alerta de Compra");
        model.addColumn("Categoría");
        model.addColumn("Descripción");
        
        try {
            while (rst.next()){
                datos[0] = rst.getString(1);
                datos[1] = rst.getObject(2);
                datos[2] = rst.getObject(3);
                datos[3] = rst.getObject(4);
                datos[4] = rst.getObject(5);
                datos[5] = rst.getObject(6);
                datos[6] = rst.getObject(7);
                datos[7] = rst.getObject(8);
                datos[8] = rst.getObject(9);
                model.addRow(datos);
            }
            
            jtblProductos.setModel(model);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void llenarCategorias() {
        String datos;
        ResultSet rst = null;
        rst = prod.obtenerCategorias();
        
        
        try {
            while (rst.next()){
                datos = rst.getString(1);
                cmbCategoria.addItem(datos);
            }
           
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
    }
}
