/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendaangelitodesktop;


import java.util.logging.Level;
import java.util.logging.Logger;



import dao.Compra;
import dao.Producto;
import dao.Proveedor;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arnold
 */
public class FrmCompras extends javax.swing.JDialog {
    
    int idProveedor=-1;
    ResultSet rst = null;
    DefaultTableModel model; 
    Proveedor prov = new Proveedor();
    Producto prod = new Producto();
    Compra comp = new Compra();
    java.awt.Frame parent;

    /**
     * Creates new form FrmCompras
     */
    public FrmCompras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        llenarProveedores();
        llenarProductos();
        iniciarDetalles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProveedor = new javax.swing.JPanel();
        txfProveedor = new javax.swing.JTextField();
        btnRegistrarProveedor = new javax.swing.JButton();
        btnSeleccionarProveedor = new javax.swing.JButton();
        spnlClientes = new javax.swing.JScrollPane();
        tblProveedores = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lblProveedor = new javax.swing.JLabel();
        lblProvSeleccionado = new javax.swing.JLabel();
        pnlProducto = new javax.swing.JPanel();
        txfProducto = new javax.swing.JTextField();
        btnNuevoProducto = new javax.swing.JButton();
        btnAgregarProducto = new javax.swing.JButton();
        spnlProductos = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        txfCantidad = new javax.swing.JTextField();
        txfCodLote = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txfFechaFab = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txfFechaVen = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txfPrecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCP = new javax.swing.JLabel();
        lblCantidadProd = new javax.swing.JLabel();
        lblT = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblFN = new javax.swing.JLabel();
        lblCompraNo = new javax.swing.JLabel();
        pnlDetalle = new javax.swing.JPanel();
        spnlDetalles = new javax.swing.JScrollPane();
        tblDetalles = new javax.swing.JTable();
        btnQuitar = new javax.swing.JButton();
        btnRegCompra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlProveedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Proveedor"));

        txfProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfProveedorActionPerformed(evt);
            }
        });
        txfProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfProveedorKeyReleased(evt);
            }
        });

        btnRegistrarProveedor.setText("Registrar Nuevo Proveedor");
        btnRegistrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProveedorActionPerformed(evt);
            }
        });

        btnSeleccionarProveedor.setText("Seleccionar Proveedor");
        btnSeleccionarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarProveedorActionPerformed(evt);
            }
        });

        tblProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spnlClientes.setViewportView(tblProveedores);

        jLabel7.setText("Buscar Proveedor:");

        lblProveedor.setText("Proveedor de esta compra:");

        lblProvSeleccionado.setText("Seleccione proveedor");

        javax.swing.GroupLayout pnlProveedorLayout = new javax.swing.GroupLayout(pnlProveedor);
        pnlProveedor.setLayout(pnlProveedorLayout);
        pnlProveedorLayout.setHorizontalGroup(
            pnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnlClientes)
                    .addGroup(pnlProveedorLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProveedorLayout.createSequentialGroup()
                        .addComponent(btnSeleccionarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(lblProveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProvSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlProveedorLayout.setVerticalGroup(
            pnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProveedorLayout.createSequentialGroup()
                .addGroup(pnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarProveedor)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spnlClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleccionarProveedor)
                    .addComponent(lblProveedor)
                    .addComponent(lblProvSeleccionado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));

        txfProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfProductoActionPerformed(evt);
            }
        });
        txfProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfProductoKeyReleased(evt);
            }
        });

        btnNuevoProducto.setText("Registrar un Nuevo Producto");
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoActionPerformed(evt);
            }
        });

        btnAgregarProducto.setText("Agregar datos a Detalle de Compra");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spnlProductos.setViewportView(tblProductos);

        txfCantidad.setText("0");
        txfCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCantidadActionPerformed(evt);
            }
        });

        jLabel1.setText("Código Lote:");

        jLabel2.setText("Fecha Fab:");

        txfFechaFab.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        jLabel3.setText("Fecha Ven:");

        txfFechaVen.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        jLabel4.setText("Cantidad por Lote:");

        jLabel5.setText("Precio por Lote:");

        txfPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPrecioActionPerformed(evt);
            }
        });

        jLabel6.setText("Buscar Producto:");

        javax.swing.GroupLayout pnlProductoLayout = new javax.swing.GroupLayout(pnlProducto);
        pnlProducto.setLayout(pnlProductoLayout);
        pnlProductoLayout.setHorizontalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnlProductos)
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProductoLayout.createSequentialGroup()
                                .addComponent(txfCodLote, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfFechaFab, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfFechaVen, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 152, Short.MAX_VALUE))
                            .addGroup(pnlProductoLayout.createSequentialGroup()
                                .addComponent(txfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregarProducto)))))
                .addContainerGap())
        );
        pnlProductoLayout.setVerticalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoProducto)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spnlProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfCodLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txfFechaFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txfFechaVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarProducto)
                    .addComponent(txfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumen"));

        lblCP.setText("Cantidad de productos:");

        lblCantidadProd.setText("0");

        lblT.setText("Total:");

        lblTotal.setText("$0.00");

        lblFN.setText("Compra N°:");

        lblCompraNo.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCompraNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCantidadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCP)
                    .addComponent(lblCantidadProd)
                    .addComponent(lblT)
                    .addComponent(lblTotal)
                    .addComponent(lblFN)
                    .addComponent(lblCompraNo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDetalle.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        tblDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spnlDetalles.setViewportView(tblDetalles);

        btnQuitar.setText("Quitar Detalle");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnlDetalles)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetalleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnQuitar))
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addComponent(spnlDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnQuitar)
                .addGap(3, 3, 3))
        );

        btnRegCompra.setText("Registrar Compra");
        btnRegCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegCompra)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfProveedorActionPerformed
        seleccionarProveedor();
        txfProveedor.setText("");
        txfProducto.requestFocus();
    }//GEN-LAST:event_txfProveedorActionPerformed

    private void txfProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfProveedorKeyReleased
        String filtro = txfProveedor.getText();
        filtrarProveedores(filtro);
    }//GEN-LAST:event_txfProveedorKeyReleased

    private void btnRegistrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProveedorActionPerformed
        FrmPersonas frame = new FrmPersonas(this.parent,true);
        frame.setVisible(true);
    }//GEN-LAST:event_btnRegistrarProveedorActionPerformed

    private void btnSeleccionarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarProveedorActionPerformed
        seleccionarProveedor();
    }//GEN-LAST:event_btnSeleccionarProveedorActionPerformed

        private int numCompra(){
        int noC=0;
        try{
            rst = null;
            rst = comp.ultimaCompra();
            while(rst.next()){
                noC=rst.getInt(1);
            }
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        noC+=1;
        return noC;
    }
    
    
    private void btnRegCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegCompraActionPerformed
        int idCompra = numCompra();
        int idPersona = idProveedor;
        int idUsuario = Variables.idUsuario;
        String idProducto="";
        int cantidad=0;
        
        String codLote="";
        String fechaFab="";
        String fechaVen="";
        double precio=0;

        if(idProveedor!=-1){
            if(tblDetalles.getModel().getRowCount()<=0){
                JOptionPane.showMessageDialog(null, "No hay compras a registrar");
            }else{
                for(int i=0;i<tblDetalles.getModel().getRowCount();i++){
                    try {
                        codLote = (String) tblDetalles.getValueAt(tblDetalles.getSelectedRow(), 3);
                        idProducto = tblDetalles.getModel().getValueAt(i, 0).toString();
                        fechaFab = (String) tblDetalles.getValueAt(tblDetalles.getSelectedRow(), 4);
                        fechaVen =  (String) tblDetalles.getValueAt(tblDetalles.getSelectedRow(), 5);
                        cantidad = Integer.parseInt(tblDetalles.getModel().getValueAt(i, 6).toString());
                        precio = Double.parseDouble(tblDetalles.getModel().getValueAt(i, 7).toString());
                        
                        rst = null;
                        rst = comp.comprar(codLote, idProducto, fechaFab, fechaVen, cantidad, precio, idCompra, idPersona, idProveedor);
                        rst.next();
                        JOptionPane.showMessageDialog(null, rst.getString(1));
                    } catch (SQLException ex) {
                        Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un Proveedor");
        }
        actualizar();
    
    }//GEN-LAST:event_btnRegCompraActionPerformed
   
    
    private void txfProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfProductoActionPerformed
        if(txfProducto.getText().length()>0){
            txfCodLote.requestFocus();
        }else{
            btnRegCompra.requestFocus();
        }
        
    }//GEN-LAST:event_txfProductoActionPerformed

    private void txfProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfProductoKeyReleased
        filtrarProductos(txfProducto.getText());
    }//GEN-LAST:event_txfProductoKeyReleased

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
        if(Variables.tipoUsuario==1){
            FrmAdministrarProducto frame = new FrmAdministrarProducto(this.parent,true);
            frame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Usuario no autorizado");
        }

    }//GEN-LAST:event_btnNuevoProductoActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        if((Integer.parseInt(txfCantidad.getText())>0) && (txfCodLote.getText()!=null)
                &&(txfFechaFab.getText()!=null)&&(txfFechaVen.getText()!=null)
                &&(Double.parseDouble(txfPrecio.getText())>0)){
            agregarDetalle(obtenerIdProducto());
        }
        txfCantidad.setText("0");
        txfCodLote.setText("");
        txfFechaFab.setText("");
        txfFechaVen.setText("");
        txfPrecio.setText("0");
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void txfCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCantidadActionPerformed
        txfPrecio.requestFocus();
    }//GEN-LAST:event_txfCantidadActionPerformed

    private void txfPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPrecioActionPerformed
        if((Integer.parseInt(txfCantidad.getText())>0) && (txfCodLote.getText()!=null)
                &&(txfFechaFab.getText()!=null)&&(txfFechaVen.getText()!=null)
                &&(Double.parseDouble(txfPrecio.getText())>0)){
        agregarDetalle(obtenerIdProducto());
        }
        txfCantidad.setText("0");
        txfCodLote.setText("");
        txfFechaFab.setText("");
        txfFechaVen.setText("");
        txfPrecio.setText("0");
    }//GEN-LAST:event_txfPrecioActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        int selectedRow = tblDetalles.getSelectedRow();

        if(selectedRow==-1){
            JOptionPane.showMessageDialog(null, "Seleccione el registro que desea quitar de la factura");
        }else{
            eliminarRegistro(selectedRow);
            resumen();
        }
    }//GEN-LAST:event_btnQuitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmCompras dialog = new FrmCompras(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void seleccionarProveedor() {
        int selectedRow=-1;
        String nombreProveedor="";
        
        selectedRow = tblProveedores.getSelectedRow();
        
        if(selectedRow==-1){
            nombreProveedor = tblProveedores.getModel().getValueAt(0, 2).toString();
            idProveedor = Integer.parseInt(tblProveedores.getModel().getValueAt(0, 0).toString());
        }else{
            nombreProveedor = tblProveedores.getModel().getValueAt(selectedRow,2).toString();
            idProveedor = Integer.parseInt(tblProveedores.getModel().getValueAt(selectedRow, 0).toString());
        }
        
        lblProvSeleccionado.setText(nombreProveedor);
     
    }

    private void llenarProveedores() {
        Object datos[] = new Object[3];
        rst = null;
        rst = prov.obtenerProveedores();
        model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("DUI");
        model.addColumn("Nombre");
        try {
            while (rst.next()){
                datos[0] = rst.getString(1);
                datos[1] = rst.getObject(2);
                datos[2] = rst.getString(6) + " " + rst.getString(7);
                model.addRow(datos);
            }
            
            tblProveedores.setModel(model);
            tblProveedores.getColumnModel().getColumn(0).setMaxWidth(0);
            tblProveedores.getColumnModel().getColumn(0).setMinWidth(0);
            tblProveedores.getColumnModel().getColumn(0).setPreferredWidth(0);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
        
    }

    private void llenarProductos() {
        Object datos[] = new Object[6];
        rst = null;
        rst = prod.productos();
        model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Producto");
        model.addColumn("Descripcion");
        model.addColumn("Existencia");
        
        try {
            while (rst.next()){
                datos[0] = rst.getString(1);
                datos[1] = rst.getObject(2);
                datos[2] = rst.getString(3);
                datos[3] = rst.getString(8);
                
                model.addRow(datos);
            }
            
            tblProductos.setModel(model);

            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
        
    }

    private void iniciarDetalles() {
        model = new DefaultTableModel();
        model.addColumn("Cod. Producto");
        model.addColumn("Producto");
        model.addColumn("Descripción");
        model.addColumn("Cod Lote");
        model.addColumn("Fecha Fab");
        model.addColumn("Fecha Ven");
        model.addColumn("Cant por Lote");
        model.addColumn("Precio Lote");
        tblDetalles.setModel(model);

    }

    private void filtrarProveedores(String filtro) {
        Object datos[] = new Object[3];
        rst = null;
        rst = prov.filtrarProveedores(filtro);
        model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("DUI");
        model.addColumn("Nombre");
        try {
            while (rst.next()){
                datos[0] = rst.getString(1);
                datos[1] = rst.getObject(2);
                datos[2] = rst.getString(6) + " " + rst.getString(7);
                model.addRow(datos);
            }
            
            tblProveedores.setModel(model);
            tblProveedores.getColumnModel().getColumn(0).setMaxWidth(0);
            tblProveedores.getColumnModel().getColumn(0).setMinWidth(0);
            tblProveedores.getColumnModel().getColumn(0).setPreferredWidth(0);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
    }

    private void filtrarProductos(String filtro) {
        Object datos[] = new Object[6];
        rst = null;
        rst = prod.productos(filtro);
        model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Producto");
        model.addColumn("Descripcion");
        model.addColumn("Existencia");
        try {
            while (rst.next()){
                datos[0] = rst.getString(1);
                datos[1] = rst.getObject(2);
                datos[2] = rst.getString(3);
                datos[3] = rst.getString(8);
                
                model.addRow(datos);
            }
            
            tblProductos.setModel(model);

            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }

    }

    private String obtenerIdProducto() {
        int selectedRow=-1;
        selectedRow = tblProductos.getSelectedRow();
        String idProd;
        
        if(selectedRow==-1){
            idProd=(String) tblProductos.getValueAt(0, 0);
            return idProd;
            
        }else{
            idProd=(String) tblProductos.getValueAt(tblProductos.getSelectedRow(), 0);
            return idProd;
        }
        
    }

    private void agregarDetalle(String idProducto) {
        Object datos[] = new Object[8];
            model = (DefaultTableModel) tblDetalles.getModel();
            rst = null;
            rst = prod.productosPorCodigo(idProducto);
            try {
                while (rst.next()){
                    datos[0] = idProducto;
                    datos[1] = rst.getObject(2);
                    datos[2] = rst.getString(3);
                    datos[3] = txfCodLote.getText().trim();
                    datos[4] = txfFechaFab.getText();
                    datos[5] = txfFechaVen.getText();
                    datos[6] = txfCantidad.getText();
                    datos[7] = txfPrecio.getText();

                    model.addRow(datos);
                    
                }

                tblDetalles.setModel(model);

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
            }
            resumen();
    }

    private void resumen() {
        int cantidad=0;
        double total=0;
        for(int i=0;i<tblDetalles.getRowCount();i++){
            cantidad+=(Integer)tblDetalles.getModel().getValueAt(i, 6);
            total+=Double.parseDouble(tblDetalles.getModel().getValueAt(i,7).toString());
        }
        lblCantidadProd.setText(" "+cantidad);
        lblTotal.setText("$ "+total);
        
    }

    private void actualizar() {
    
        txfCantidad.setText("0");
        txfProveedor.setText("");
        txfProducto.setText("");
        txfCodLote.setText("");
        txfFechaFab.setText("");
        txfFechaVen.setText("");
        txfPrecio.setText("0");
        
        llenarProveedores();
        llenarProductos();
        iniciarDetalles();
        lblCompraNo.setText(" "+numCompra());
    

    }

    private void eliminarRegistro(int row) {
        ((DefaultTableModel)tblDetalles.getModel()).removeRow(row);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnRegCompra;
    private javax.swing.JButton btnRegistrarProveedor;
    private javax.swing.JButton btnSeleccionarProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCP;
    private javax.swing.JLabel lblCantidadProd;
    private javax.swing.JLabel lblCompraNo;
    private javax.swing.JLabel lblFN;
    private javax.swing.JLabel lblProvSeleccionado;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblT;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JPanel pnlProducto;
    private javax.swing.JPanel pnlProveedor;
    private javax.swing.JScrollPane spnlClientes;
    private javax.swing.JScrollPane spnlDetalles;
    private javax.swing.JScrollPane spnlProductos;
    private javax.swing.JTable tblDetalles;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTable tblProveedores;
    private javax.swing.JTextField txfCantidad;
    private javax.swing.JTextField txfCodLote;
    private javax.swing.JFormattedTextField txfFechaFab;
    private javax.swing.JFormattedTextField txfFechaVen;
    private javax.swing.JTextField txfPrecio;
    private javax.swing.JTextField txfProducto;
    private javax.swing.JTextField txfProveedor;
    // End of variables declaration//GEN-END:variables

    
}
