/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendaangelitodesktop;

import dao.Usuario;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author vladi
 */
public class FrmLogin extends javax.swing.JDialog {
    private int width, height;
    private ResultSet rst;
    private Usuario usu = new Usuario();

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void posicionar(int x, int y){
        //272,158
        x = (x/2)-(this.getSize().width/2);
        y = (y/2)-(this.getSize().height/2);
        this.setLocation(x, y);
    }
    
    public void limpiar(){
        txfUsuario.setText("");
        txfPass.setText("");
        txfUsuario.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogIn = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txfUsuario = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        lblForgPass = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        txfPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlLogIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIniciarSesion.setText("Iniciar Sesión");

        lblUsuario.setText("Usuario:");

        txfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfUsuarioActionPerformed(evt);
            }
        });

        lblPass.setText("Contraseña:");

        lblForgPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblForgPass.setText("Olvidé mi contraseña");
        lblForgPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblForgPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblForgPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblForgPassMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblForgPassMouseReleased(evt);
            }
        });

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        txfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLogInLayout = new javax.swing.GroupLayout(pnlLogIn);
        pnlLogIn.setLayout(pnlLogInLayout);
        pnlLogInLayout.setHorizontalGroup(
            pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIniciarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblForgPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlLogInLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlLogInLayout.createSequentialGroup()
                        .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txfPass))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlLogInLayout.setVerticalGroup(
            pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIniciarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(txfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblForgPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        posicionar(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height);
    }//GEN-LAST:event_formWindowOpened

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        loggearse();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfUsuarioActionPerformed
        loggearse();
    }//GEN-LAST:event_txfUsuarioActionPerformed

    private void txfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPassActionPerformed
        loggearse();
    }//GEN-LAST:event_txfPassActionPerformed

    private void lblForgPassMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgPassMouseReleased
        String alias;
        String dui="";
        String nit="";
        String nombre="";
        String apellido="";
        int tipoUsuario=0;
        int idUsuario=0;
        
        alias = JOptionPane.showInputDialog(this, "Ingrese su nombre de usuario");
        rst = usu.usuarios(alias);
        
        try {
            if (rst.next()){
                idUsuario = rst.getInt(1);
                dui = rst.getString(9);
                nit = rst.getString(10);
                nombre = rst.getString(13);
                apellido = rst.getString(14);
                tipoUsuario = rst.getInt(3);
                
                if(tipoUsuario!=1){
                    JOptionPane.showMessageDialog(this, "Por favor, póngase en contacto con el administrador");
                } else {
                    if(JOptionPane.showInputDialog(this, "Ingrese su DUI con guiones (########-#)").equals(dui)){
                        if(JOptionPane.showInputDialog(this, "Ingrese su NIT con guiones (####-######-###-#)").equals(nit)){
                            if(JOptionPane.showInputDialog(this, "Ingrese su primer y segundo nombre (ej. Juan José)").equals(nombre)){
                                if(JOptionPane.showInputDialog(this, "Ingrese su primer y segundo apellido (ej. Hernández Gonzáles)").equals(apellido)){
                                    nuevoPass(idUsuario);
                                } else {
                                    JOptionPane.showMessageDialog(this,"Apellidos incorrectos");
                                }
                            } else {
                                JOptionPane.showMessageDialog(this,"Nombre incorrectos");
                            }
                        } else{
                            JOptionPane.showMessageDialog(this,"NIT incorrecto");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this,"DUI incorrecto");
                    }
                }
                
                
            } else {
                JOptionPane.showMessageDialog(this,"El usuario "+alias+" no se encuentra registrado");
                Variables.idUsuario = 0;
                Variables.tipoUsuario = 0;
                Variables.nombreUsuario = "NULL";
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_lblForgPassMouseReleased

    private void lblForgPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgPassMouseEntered
        lblForgPass.setForeground(Color.red);
    }//GEN-LAST:event_lblForgPassMouseEntered

    private void lblForgPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgPassMouseExited
        lblForgPass.setForeground(Color.black);
    }//GEN-LAST:event_lblForgPassMouseExited

    private void nuevoPass(int idUsuario){
        String nuevoPass;
        do{
            nuevoPass=JOptionPane.showInputDialog(this, "Ingrese su nueva contraseña");
        }while(!nuevoPass.equals(JOptionPane.showInputDialog(this, "Repita su nueva contraseña")));
        
        usu.cambiarPass(idUsuario, nuevoPass);
        JOptionPane.showMessageDialog(this, "Contraseña cambiada con éxito");
    }
    
    private void loggearse(){
        String usuario = txfUsuario.getText();
        String password="";
        
        rst=null;
        
        for(int i=0;i<txfPass.getPassword().length;i++){
            password+=txfPass.getPassword()[i];
        }
        
        rst = usu.usuarios(usuario, password);
        
        try {
            if (rst.next()){
                Variables.idUsuario = rst.getInt(1);
                Variables.tipoUsuario = rst.getInt(3);
                Variables.nombreUsuario = rst.getString(13)+" "+rst.getString(14);
                limpiar();
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this,"Usuario o contraseña incorrectos");
                Variables.idUsuario = 0;
                Variables.tipoUsuario = 0;
                Variables.nombreUsuario = "NULL";
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmLogin dialog = new FrmLogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel lblForgPass;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlLogIn;
    private javax.swing.JPasswordField txfPass;
    private javax.swing.JTextField txfUsuario;
    // End of variables declaration//GEN-END:variables
}
