/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendaangelitodesktop;

import dao.Backup;
import java.awt.Toolkit;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.JOptionPane;

/**
 *
 * @author vladi
 */
public class FrmPrincipal extends javax.swing.JFrame {
    //FrmLogin login;
    ResultSet rst;
    Backup bu = new Backup();
    int width = Toolkit.getDefaultToolkit().getScreenSize().width;
    int height = Toolkit.getDefaultToolkit().getScreenSize().height;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }
    
//    public Image getIconImage(){
//        Image retValue = Toolkit.getDefaultToolkit().getImage("recursos.iconos/IconoBarra.png");
//        return retValue;
//    }
    
    private void desactivarPanel(){
        btnCompras.setEnabled(false);
        btnDesconectar.setEnabled(false);
        btnFacturar.setEnabled(false);
        btnProductos.setEnabled(false);
        btnRegistrar.setEnabled(false);
        btnReportes.setEnabled(false);
        btnSalir.setEnabled(false);
    }
    
    private void activarPanelAdm(){
        btnCompras.setEnabled(true);
        btnDesconectar.setEnabled(true);
        btnFacturar.setEnabled(true);
        btnProductos.setEnabled(true);
        btnRegistrar.setEnabled(true);
        btnReportes.setEnabled(true);
        btnSalir.setEnabled(true);
    }
    
    private void activarPanelVendedor(){
        btnCompras.setEnabled(false);
        btnDesconectar.setEnabled(true);
        btnFacturar.setEnabled(true);
        btnProductos.setEnabled(false);
        btnRegistrar.setEnabled(true);
        btnReportes.setEnabled(false);
        btnSalir.setEnabled(false);
    }
    
    private void reposicionarBtn(){
        int x=32;
        int y=18;
        
        reposicionarBtn(btnFacturar,8,4);
        reposicionarBtn(btnCompras,14,4);
        reposicionarBtn(btnRegistrar,20,4);
        reposicionarBtn(btnReportes,11,9);
        reposicionarBtn(btnProductos,17,9);
        reposicionarBtn(btnDesconectar,22,13);
        reposicionarBtn(btnSalir,27,13);
        
    }
    
    private void reposicionarBtn(JButton btn, int x, int y){
        btn.setLocation(width*x/32, height*y/18);
    }
    
    private void redimensionarBtn(){
        redimensionarBtn(btnCompras);
        redimensionarBtn(btnDesconectar);
        redimensionarBtn(btnFacturar);
        redimensionarBtn(btnProductos);
        redimensionarBtn(btnRegistrar);
        redimensionarBtn(btnReportes);
        redimensionarBtn(btnSalir);
    }
    
    private void redimensionarBtn(JButton btn){
        int width=(this.width/32)*4;
        int height=(this.height/18)*3;
        btn.setSize(width, height);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnReportes = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnFacturar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnDesconectar = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        mnuGenerarBackup = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tienda Angelito");
        setExtendedState(MAXIMIZED_BOTH);
        setIconImage(getIconImage());
        setName("Principal"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/logopequeño.png"))); // NOI18N
        lblTitulo.setMaximumSize(new java.awt.Dimension(270, 170));
        lblTitulo.setPreferredSize(new java.awt.Dimension(200, 180));

        btnReportes.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/reporte1.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setBorder(null);
        btnReportes.setBorderPainted(false);
        btnReportes.setContentAreaFilled(false);
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReportes.setFocusPainted(false);
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportes.setIconTextGap(2);
        btnReportes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/reporte3.png"))); // NOI18N
        btnReportes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/reporte2.png"))); // NOI18N
        btnReportes.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnProductos.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/productos1.png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setBorder(null);
        btnProductos.setBorderPainted(false);
        btnProductos.setContentAreaFilled(false);
        btnProductos.setFocusPainted(false);
        btnProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProductos.setIconTextGap(2);
        btnProductos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/productos3.png"))); // NOI18N
        btnProductos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/productos2.png"))); // NOI18N
        btnProductos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnFacturar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnFacturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/Factura1.png"))); // NOI18N
        btnFacturar.setText("Facturar");
        btnFacturar.setBorder(null);
        btnFacturar.setBorderPainted(false);
        btnFacturar.setContentAreaFilled(false);
        btnFacturar.setFocusPainted(false);
        btnFacturar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFacturar.setIconTextGap(2);
        btnFacturar.setMaximumSize(new java.awt.Dimension(1000, 1000));
        btnFacturar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/Factura3.png"))); // NOI18N
        btnFacturar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/Factura2.png"))); // NOI18N
        btnFacturar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnFacturar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturarActionPerformed(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/registrar1.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setIconTextGap(2);
        btnRegistrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/registrar3.png"))); // NOI18N
        btnRegistrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/registrar2.png"))); // NOI18N
        btnRegistrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRegistrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnDesconectar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnDesconectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/desconectar1.png"))); // NOI18N
        btnDesconectar.setText("Desconectar");
        btnDesconectar.setBorder(null);
        btnDesconectar.setBorderPainted(false);
        btnDesconectar.setContentAreaFilled(false);
        btnDesconectar.setFocusPainted(false);
        btnDesconectar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDesconectar.setIconTextGap(2);
        btnDesconectar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/desconectar3.png"))); // NOI18N
        btnDesconectar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/desconectar2.png"))); // NOI18N
        btnDesconectar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnDesconectar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });

        btnCompras.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/compras1.png"))); // NOI18N
        btnCompras.setText("Compras");
        btnCompras.setBorder(null);
        btnCompras.setBorderPainted(false);
        btnCompras.setContentAreaFilled(false);
        btnCompras.setFocusPainted(false);
        btnCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompras.setIconTextGap(2);
        btnCompras.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/compras3.png"))); // NOI18N
        btnCompras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/compras2.png"))); // NOI18N
        btnCompras.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCompras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/cerrar1.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setFocusPainted(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setIconTextGap(2);
        btnSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/cerrar3.png"))); // NOI18N
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/cerrar2.png"))); // NOI18N
        btnSalir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Herramientas");
        jMenu2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N

        mnuGenerarBackup.setText("Generar back-up");
        mnuGenerarBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGenerarBackupActionPerformed(evt);
            }
        });
        jMenu2.add(mnuGenerarBackup);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnProductos)
                        .addGap(18, 18, 18)
                        .addComponent(btnFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCompras)
                        .addGap(18, 18, 18)
                        .addComponent(btnDesconectar)
                        .addGap(10, 10, 10)
                        .addComponent(btnRegistrar))
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReportes)
                    .addComponent(btnProductos)
                    .addComponent(btnFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCompras)
                    .addComponent(btnDesconectar)
                    .addComponent(btnRegistrar))
                .addGap(11, 11, 11)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturarActionPerformed
        FrmFactura fac=new FrmFactura(this, false);
        fac.setVisible(true);
    }//GEN-LAST:event_btnFacturarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        redimensionarBtn();
        reposicionarBtn();
        desactivarPanel();
        Variables.login = new FrmLogin(this,true);
        Variables.login.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        switch (Variables.tipoUsuario){
            case 0:
                desactivarPanel();
                break;
            case 1:
                activarPanelAdm();
                break;
            case 2:
                activarPanelVendedor();
                break;
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        FrmAdministrarProducto prod= new FrmAdministrarProducto(this,true);
        prod.setVisible(true);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        // Agregar formulario compras
        FrmCompras prod= new FrmCompras(this,true);
        prod.setVisible(true);
    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
        desactivarPanel();
        Variables.idUsuario=0;
        Variables.tipoUsuario=0;
        Variables.login.setVisible(true);
    }//GEN-LAST:event_btnDesconectarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        FrmPersonas per=new FrmPersonas(this,true);
        per.setVisible(true);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void mnuGenerarBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGenerarBackupActionPerformed
        FileReader fr;
        JFileChooser chooser = new JFileChooser();
        FileWriter fw;
        String linea;
        JOptionPane.showMessageDialog(this, "Esta acción puede demorar algunos minutos.");
        chooser.setCurrentDirectory(new File("/home/me/Desktop"));
        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
            try {
                fw = new FileWriter(chooser.getSelectedFile()+".txt");
                fr = new FileReader(new File(this.getClass().getResource("../recursos/db/database").toURI()));
                BufferedReader bf = new BufferedReader(fr);
                while((linea = bf.readLine()) != null){
                    fw.write(linea+System.getProperty("line.separator"));
                }
                fw.write(System.getProperty("line.separator")+buPersonas());
                fw.write(buClientes());
                fw.write(buEmpleados());
                fw.write(buProveedores());
                fw.write(buTiposUsuario());
                fw.write(buUsuarios());
                fw.write(buFacturas());
                fw.write(buCompras());
                fw.write(buCategorias());
                fw.write(buProductos());
                fw.write(buDetallesFactura());
                fw.write(buLotes());
                fw.write(buDetallesCompra());
                fw.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_mnuGenerarBackupActionPerformed

    private String buPersonas(){
        String insertPersonas="";
        rst = null;
        rst = bu.getPersonas();
        
        try {
            while (rst.next()){
                insertPersonas = insertPersonas + "INSERT INTO persona VALUES("
                        +nullable(rst.getString(1))+", "
                        +nullable(rst.getString(2))+", "
                        +nullable(rst.getString(3))+", "
                        +nullable(rst.getString(4))+", "
                        +nullable(rst.getString(5))+", "
                        +nullable(rst.getString(6))+", "
                        +nullable(rst.getString(7))+", "
                        +nullable(rst.getString(8))+", "
                        +nullable(rst.getString(9))+", "
                        +nullable(rst.getString(10))+", "
                        +nullable(rst.getString(11))+");";
                insertPersonas = insertPersonas + System.getProperty("line.separator");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
        
        return insertPersonas;
    }
    
    private String buClientes(){
        String insertClientes="";
        rst = null;
        rst = bu.getClientes();
        
        try {
            while (rst.next()){
                insertClientes = insertClientes + "INSERT INTO cliente VALUES("
                        +nullable(rst.getString(1))+");";
                insertClientes = insertClientes + System.getProperty("line.separator");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
        
        return insertClientes;
    }
    
    private String buEmpleados(){
        String insertEmpleados="";
        rst = null;
        rst = bu.getEmpleados();
        
        try {
            while (rst.next()){
                insertEmpleados = insertEmpleados + "INSERT INTO empleado VALUES("
                        +nullable(rst.getString(1))+");";
                insertEmpleados = insertEmpleados + System.getProperty("line.separator");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
        
        return insertEmpleados;
    }
    
    private String buProveedores(){
        String insertProveedores="";
        rst = null;
        rst = bu.getProveedores();
        
        try {
            while (rst.next()){
                insertProveedores = insertProveedores + "INSERT INTO proveedor VALUES("
                        +nullable(rst.getString(1))+");";
                insertProveedores = insertProveedores + System.getProperty("line.separator");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
        
        return insertProveedores;
    }
    
    private String buTiposUsuario(){
        String insertTiposUsuario="";
        rst = null;
        rst = bu.getTiposDeUsuario();
        
        try {
            while (rst.next()){
                insertTiposUsuario = insertTiposUsuario + "INSERT INTO tipousuario VALUES("
                    +nullable(rst.getString(1))+", "
                    +nullable(rst.getString(2))+");";
                insertTiposUsuario = insertTiposUsuario + System.getProperty("line.separator");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
        
        return insertTiposUsuario;
    }
    
    private String buUsuarios(){
        String insertUsuarios="";
        rst = null;
        rst = bu.getUsuarios();
        
        try {
            while (rst.next()){
                insertUsuarios = insertUsuarios + "INSERT INTO usuario VALUES("
                        +nullable(rst.getString(1))+", "
                        +nullable(rst.getString(2))+", "
                        +nullable(rst.getString(3))+", "
                        +nullable(rst.getString(4))+", "
                        +nullable(rst.getString(5))+");";
                insertUsuarios = insertUsuarios + System.getProperty("line.separator");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
        
        return insertUsuarios;
    }
    
    private String buFacturas(){
        String insertFacturas="";
        rst = null;
        rst = bu.getFacturas();
        
        try {
            while (rst.next()){
                insertFacturas = insertFacturas + "INSERT INTO factura VALUES("
                        +nullable(rst.getString(1))+", "
                        +nullable(rst.getString(2))+", "
                        +nullable(rst.getString(3))+", "
                        +nullable(rst.getString(4))+");";
                insertFacturas = insertFacturas + System.getProperty("line.separator");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
        
        return insertFacturas;
    }
    
    private String buCompras(){
        String insertCompras="";
        rst = null;
        rst = bu.getCompras();
        
        try {
            while (rst.next()){
                insertCompras = insertCompras + "INSERT INTO compra VALUES("
                        +nullable(rst.getString(1))+", "
                        +nullable(rst.getString(2))+", "
                        +nullable(rst.getString(3))+", "
                        +nullable(rst.getString(4))+");";
                insertCompras = insertCompras + System.getProperty("line.separator");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
        
        return insertCompras;
    }
    
    private String buCategorias(){
        String insertCategorias="";
        rst = null;
        rst = bu.getCategorias();
        
        try {
            while (rst.next()){
                insertCategorias = insertCategorias + "INSERT INTO categoria VALUES("
                        +nullable(rst.getString(1))+", "
                        +nullable(rst.getString(2))+");";
                insertCategorias = insertCategorias + System.getProperty("line.separator");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
        
        return insertCategorias;
    }
    
    private String buProductos(){
        String insertProductos="";
        rst = null;
        rst = bu.getProductos();
        
        try {
            while (rst.next()){
                insertProductos = insertProductos + "INSERT INTO producto VALUES("
                        +nullable(rst.getString(1))+", "
                        +nullable(rst.getString(2))+", "
                        +nullable(rst.getString(3))+", "
                        +nullable(rst.getString(4))+", "
                        +nullable(rst.getString(5))+", "
                        +nullable(rst.getString(6))+", "
                        +nullable(rst.getString(7))+", "
                        +nullable(rst.getString(8))+", "
                        +nullable(rst.getString(9))+", "
                        +nullable(rst.getString(10))+");";
                insertProductos = insertProductos + System.getProperty("line.separator");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
        
        return insertProductos;
    }
    
    private String buDetallesFactura(){
        String insertDetallesFactura="";
        rst = null;
        rst = bu.getDetallesFactura();
        
        try {
            while (rst.next()){
                insertDetallesFactura = insertDetallesFactura + "INSERT INTO detallefactura VALUES("
                        +nullable(rst.getString(1))+", "
                        +nullable(rst.getString(2))+", "
                        +nullable(rst.getString(3))+", "
                        +nullable(rst.getString(4))+");";
                insertDetallesFactura = insertDetallesFactura + System.getProperty("line.separator");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
        
        return insertDetallesFactura;
    }
    
    private String buLotes(){
        String insertLotes="";
        rst = null;
        rst = bu.getLotes();
        
        try {
            while (rst.next()){
                insertLotes = insertLotes + "INSERT INTO lote VALUES("
                        +nullable(rst.getString(1))+", "
                        +nullable(rst.getString(2))+", "
                        +nullable(rst.getString(3))+", "
                        +nullable(rst.getString(4))+", "
                        +nullable(rst.getString(5))+", "
                        +nullable(rst.getString(6))+", "
                        +nullable(rst.getString(7))+");";
                insertLotes = insertLotes + System.getProperty("line.separator");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
        
        return insertLotes;
    }
    
    private String buDetallesCompra(){
        String insertDetallesCompra="";
        rst = null;
        rst = bu.getDetallesCompra();
        
        try {
            while (rst.next()){
                insertDetallesCompra = insertDetallesCompra + "INSERT INTO detallecompra VALUES("
                        +nullable(rst.getString(1))+", "
                        +nullable(rst.getString(2))+");";
                insertDetallesCompra = insertDetallesCompra + System.getProperty("line.separator");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
        
        return insertDetallesCompra;
    }
    
    private String nullable(String dato){
        if(dato==null){
            dato="null";
        }
        if(!dato.equals("null")){
            dato = "'"+dato+"'";
        }
        
        return dato;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JButton btnFacturar;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuItem mnuGenerarBackup;
    // End of variables declaration//GEN-END:variables
}
