/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendaangelitodesktop.editar;

import dao.Categoria;
import dao.Producto;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import tiendaangelitodesktop.FrmCategoria;

/**
 *
 * @author Arnold
 */
public class FrmEditarProducto extends javax.swing.JDialog {
    Producto prod =new Producto();
    Categoria cat = new Categoria();
    
    Frame parent;
    
    String codInicial;
    String nomInicial;
    int existenciaInicial;
    
    String codigo;
    String nombre;
    String descripcion;
    double precioDetalle;
    double precioMayoreo;
    double iva;
    int cantidadMinima;
    int alerta;
    int existencia;
        
    int codigoExistente=0;
    String nomExistente=null;
        
    int categoriaInt=1;
    String categoriaS;
        
    ResultSet rst = null;
    ResultSet codigoReg=null;
    ResultSet nombres=null;
    
    

    /**
     * Creates new form FrmEditarProducto
     */
    public FrmEditarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        llenarCategorias();
    }
    
    public FrmEditarProducto(java.awt.Frame parent, boolean modal,Producto prod, String codProdEd,
                String nomProdEd,String descProdEd,Double precDetalleEd, Double precMayoreoEd,
                Double ivaEd,int minMayoreoEd,int existenciaEd,int alertaEd,String nomCategoriaEd) {
        super(parent, modal);
        
        this.parent=parent;
        initComponents();
        llenarCategorias();
        
        codInicial=codProdEd;
        nomInicial=nomProdEd;
        existenciaInicial=existenciaEd;
        
        
        
        txfCodProducto.setText(codProdEd);
        txfNomProducto.setText(nomProdEd);
        txfDescProducto.setText(descProdEd);
        txfPrecDetalle.setText(String.valueOf(precDetalleEd));
        txfPrecMayoreo.setText(String.valueOf(precMayoreoEd));
        txfIva.setText(String.valueOf(ivaEd));
        txfMinMayoreo.setText(String.valueOf(minMayoreoEd));
        txfExistencia.setText(String.valueOf(existenciaEd));
        txfAlerta.setText(String.valueOf(alertaEd));
        cmbCategoria.setSelectedItem(nomCategoriaEd);
        
        codigo=txfCodProducto.getText().trim();
        nombre=txfNomProducto.getText().trim();
    

        
        
        this.prod = prod;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblCategoria3 = new javax.swing.JLabel();
        lblCategoria4 = new javax.swing.JLabel();
        lblCategoria5 = new javax.swing.JLabel();
        lblCategoria6 = new javax.swing.JLabel();
        lblCategoria7 = new javax.swing.JLabel();
        lblCategoria8 = new javax.swing.JLabel();
        lblCategoria9 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        lblCategoria11 = new javax.swing.JLabel();
        lblCategoria10 = new javax.swing.JLabel();
        txfPrecDetalle = new javax.swing.JFormattedTextField();
        txfPrecMayoreo = new javax.swing.JFormattedTextField();
        txfIva = new javax.swing.JFormattedTextField();
        txfMinMayoreo = new javax.swing.JFormattedTextField();
        txfExistencia = new javax.swing.JFormattedTextField();
        txfAlerta = new javax.swing.JFormattedTextField();
        lblCategoria12 = new javax.swing.JLabel();
        lblCategoria13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnNuevaCat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblCategoria = new javax.swing.JLabel();
        lblCategoria1 = new javax.swing.JLabel();
        lblCategoria2 = new javax.swing.JLabel();
        txfCodProducto = new javax.swing.JTextField();
        txfNomProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txfDescProducto = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCategoria3.setText("(*) Precio Detalle:");

        lblCategoria4.setText("(*) Precio Mayoreo:");

        lblCategoria5.setText("(*) IVA Aplicable:");

        lblCategoria6.setText("(*) Cantidad Mínima de Mayoreo:");

        lblCategoria7.setText("Existencia:");

        lblCategoria8.setText("(*) Avisar cuando queden");

        lblCategoria9.setText("Categoría:");

        lblCategoria11.setText("en existencia");

        lblCategoria10.setText("%");

        txfPrecDetalle.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        txfPrecMayoreo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        txfIva.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        txfMinMayoreo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        txfExistencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        txfAlerta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        lblCategoria12.setText("$");

        lblCategoria13.setText("$");

        jLabel1.setText("(*) Campos obligatorios");

        btnNuevaCat.setText("Nueva Categoria");
        btnNuevaCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCategoria5)
                                    .addComponent(lblCategoria6)
                                    .addComponent(lblCategoria7)
                                    .addComponent(lblCategoria8)
                                    .addComponent(lblCategoria9))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCategoria3)
                                    .addComponent(lblCategoria4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblCategoria13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCategoria12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(4, 4, 4)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txfExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCategoria11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txfIva, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCategoria10))
                            .addComponent(txfPrecDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfPrecMayoreo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfMinMayoreo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNuevaCat)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria3)
                    .addComponent(txfPrecDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria4)
                    .addComponent(txfPrecMayoreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria5)
                    .addComponent(lblCategoria10)
                    .addComponent(txfIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria6)
                    .addComponent(txfMinMayoreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria7)
                    .addComponent(lblCategoria11)
                    .addComponent(txfExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria8)
                    .addComponent(txfAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria9)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevaCat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        lblCategoria.setText("(*) Código de Producto:");

        lblCategoria1.setText("(*) Nombre del Producto:");

        lblCategoria2.setText("Descripción");

        txfCodProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txfCodProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfCodProductoKeyPressed(evt);
            }
        });

        txfDescProducto.setColumns(20);
        txfDescProducto.setLineWrap(true);
        txfDescProducto.setRows(5);
        txfDescProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfDescProductoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txfDescProducto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCategoria1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfNomProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCategoria2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCategoria)
                        .addGap(18, 18, 18)
                        .addComponent(txfCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(txfCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria1)
                    .addComponent(txfNomProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCategoria2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel2.setText("Editar Producto");

        btnGuardar.setText("Guardar Cambios");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(387, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(38, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfCodProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfCodProductoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCodProductoKeyPressed

    private void txfDescProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfDescProductoKeyPressed

        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_TAB){
            txfPrecDetalle.requestFocus();
        }

    }//GEN-LAST:event_txfDescProductoKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        codigo=txfCodProducto.getText().trim();
        nombre=txfNomProducto.getText().trim();
        
        if(!codigo.equals(codInicial)){
            
            int dialogButton = JOptionPane.YES_NO_OPTION;
                    JOptionPane.showConfirmDialog (null, "Se ha modificado el código del producto ¿Está usted seguro que desea editarlo?","WARNING", 
                            dialogButton);
                    
                    if(dialogButton == JOptionPane.YES_OPTION) {
                        //System.exit(0);
                        editarProducto();
                        
                        if(dialogButton == JOptionPane.NO_OPTION) {
                            remove(dialogButton);
                        }
                    }
        }else if(Integer.parseInt(txfExistencia.getText().trim())!=existenciaInicial){
            int dialogButton = JOptionPane.YES_NO_OPTION;
                    JOptionPane.showConfirmDialog (null, "Se ha modificado la existencia del producto. Esta debería cambiar únicamente por compras y ventas. ¿Está usted seguro que desea editarlo?","WARNING", 
                            dialogButton);
                    
                    if(dialogButton == JOptionPane.YES_OPTION) {
                        //System.exit(0);
                        editarProducto();
                        
                        if(dialogButton == JOptionPane.NO_OPTION) {
                            remove(dialogButton);
                        }
                    }
            
        }else{
            editarProducto();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevaCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaCatActionPerformed
        FrmCategoria catego = new FrmCategoria(this.parent, true);
        catego.setVisible(true);
    }//GEN-LAST:event_btnNuevaCatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmEditarProducto dialog = new FrmEditarProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void llenarCategorias() {
        String datos;
        ResultSet rst = null;
        rst = prod.obtenerCategorias();
        
        
        try {
            while (rst.next()){
                datos = rst.getString(1);
                cmbCategoria.addItem(datos);
            }
           
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void hacerCambios(){
        descripcion=txfDescProducto.getText().trim();
                        precioDetalle=Double.parseDouble(txfPrecDetalle.getText());
                        precioMayoreo=Double.parseDouble(txfPrecMayoreo.getText());
                        iva=Double.parseDouble(txfIva.getText());
                        cantidadMinima=Integer.parseInt(txfMinMayoreo.getText());
                        alerta=Integer.parseInt(txfAlerta.getText());
                        existencia=Integer.parseInt(txfExistencia.getText());
                        

                        prod.modificarProducto(codInicial, codigo, nombre, descripcion, precioDetalle, precioMayoreo, iva, cantidadMinima, existencia, alerta, categoriaInt);
        
                        
                        JOptionPane.showMessageDialog(null, "Producto modificado de forma exitosa");
                        this.dispose();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevaCat;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCategoria1;
    private javax.swing.JLabel lblCategoria10;
    private javax.swing.JLabel lblCategoria11;
    private javax.swing.JLabel lblCategoria12;
    private javax.swing.JLabel lblCategoria13;
    private javax.swing.JLabel lblCategoria2;
    private javax.swing.JLabel lblCategoria3;
    private javax.swing.JLabel lblCategoria4;
    private javax.swing.JLabel lblCategoria5;
    private javax.swing.JLabel lblCategoria6;
    private javax.swing.JLabel lblCategoria7;
    private javax.swing.JLabel lblCategoria8;
    private javax.swing.JLabel lblCategoria9;
    private javax.swing.JFormattedTextField txfAlerta;
    private javax.swing.JTextField txfCodProducto;
    private javax.swing.JTextArea txfDescProducto;
    private javax.swing.JFormattedTextField txfExistencia;
    private javax.swing.JFormattedTextField txfIva;
    private javax.swing.JFormattedTextField txfMinMayoreo;
    private javax.swing.JTextField txfNomProducto;
    private javax.swing.JFormattedTextField txfPrecDetalle;
    private javax.swing.JFormattedTextField txfPrecMayoreo;
    // End of variables declaration//GEN-END:variables


    private void editarProducto() {
    
        if ("".equals(txfCodProducto.getText().trim())||"".equals(txfNomProducto.getText().trim())
                ||"".equals(txfPrecDetalle.getText().trim())
                ||"".equals(txfPrecMayoreo.getText().trim())||"".equals(txfIva.getText().trim())
                ||"".equals(txfMinMayoreo.getText().trim())||"".equals(txfAlerta.getText().trim())
                ||txfCodProducto.getText()==null||txfNomProducto.getText()==null
                ||txfPrecDetalle.getText()==null
                ||txfPrecMayoreo.getText()==null||txfIva.getText()==null
                ||txfMinMayoreo.getText()==null||txfAlerta.getText()==null) {
            JOptionPane.showMessageDialog(null, "Por favor, introduzca todos los datos obligatorios", 
                    null, JOptionPane.ERROR_MESSAGE);
           
        } else {
            codigo= txfCodProducto.getText().trim();
            nombre= txfNomProducto.getText().trim();
            categoriaS = cmbCategoria.getSelectedItem().toString();
            rst = prod.obtenerIdCategoria(categoriaS);
            codigoReg=prod.obtenerCodigos(codigo);
            nombres=prod.mostrarNombres(nombre);
            int contarNombres=0;
            int codEnBase=0;

            
            try {
                while (rst.next()){
                    categoriaInt =rst.getInt(1);
                }
                
                while (codigoReg.next()){
                    codEnBase=codigoReg.getInt(1);
                }


                while (nombres.next()){
                    nomExistente=nombres.getString(1);
                    
                    if(nomExistente!=null){
                        contarNombres=1;
                    }
                }
                
                if (codInicial.equals(codigo) && nomInicial.equals(nombre)){
                    hacerCambios();
                        
                        
                }else if (codInicial.equals(codigo) && !nomInicial.equals(nombre)) {
                    if (contarNombres==1){
                        JOptionPane.showMessageDialog(null, "Nombre de Producto Existente. No se puede asignar el mismo nombre a un nuevo producto", null, JOptionPane.ERROR_MESSAGE);
                        txfNomProducto.requestFocus();
                        
                    }else{
                        hacerCambios();
                    }

                }else if (!codInicial.equals(codigo) && nomInicial.equals(nombre)) {
                    if(codEnBase==1){
                        JOptionPane.showMessageDialog(null, "Código de Producto Existente. Asigne un código distinto", null, JOptionPane.ERROR_MESSAGE);
                        txfCodProducto.requestFocus();
                    }else{
                        hacerCambios();
                    }
                    
                    
                
                }else if (!codInicial.equals(codigo) && !nomInicial.equals(nombre)) {
                    if (contarNombres==1){
                        JOptionPane.showMessageDialog(null, "Nombre de Producto Existente. No se puede asignar el mismo nombre a un nuevo producto", null, JOptionPane.ERROR_MESSAGE);
                        txfNomProducto.requestFocus();
                        
                    }else if(codEnBase==1){
                        JOptionPane.showMessageDialog(null, "Código de Producto Existente. Asigne un código distinto", null, JOptionPane.ERROR_MESSAGE);
                        txfCodProducto.requestFocus();
                    }else{
                        hacerCambios();
                    }
                    
                    
                    
                }
            

            
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
            }
         
        }
        
    }
}
